### ISSUE TITLE
Leading zeros in nodes names

### ISSUE THREAD

**Issue by torkelsson** [sgas/bart#14]
Another report from Magnus Ullner at Lunarc:

The second one is only a bug, if you want leading zeros in your node names.

               for sequence in parts[1].split(','):
                   sequence = sequence.rstrip(']')
                   #Bug 2: Node names with leading zeros get shortened to the integer value in node ranges
                   if '-' in  sequence:
                       numbers = sequence.split('-')
                       #New line
                       numlength = len(numbers[0])

                       for i in range(int(numbers[0]),int(numbers[1])+1):
                           #nodes.append(parts[0] + str(i))
                           nodes.append(parts[0] + "{:0>{width}}".format(i,width=numlength))
                   else:
                       nodes.append(parts[0] + sequence)

**Comment by edelmann** [comment]
Merged with hpc2n/bart, thanks!
