### ISSUE TITLE
state file not updated unless records have been written

### ISSUE THREAD

**Issue by bhmevik** [sgas/bart#20]
in generateUsageRecords() bart/slurm.py, the self.state is updated to the end time of the period for which it has searched for jobs, but only if there was a job that finished in that time period. This has the following problem: If you start with statefile_default large enough to begin checking before the first job was run, or if you hit a period longer than max_days where no job fihished, the statefile will never be updated, and bart will thus stop reporting jobs.
I believe self.state should be updated the the end time of the period even if no jobs finished in that period, because we then _know_ that no jobs finished there, so there is no point searching the same period again. (If the end time is _now_, it might be an idea to set self.state to a time slightly in the past, in case there is a lag between when a job has finishd and sacct reporting it.)
Or is there something I've misunderstood?

**Comment by kmjonsson** [comment]
The reason for not updating the state was that if the slurm controller failed to give output for some reason it would not skip jobs due to that.

But I see your problem.

**Comment by bhmevik** [comment]
I see...  That is a point...  Might need a little more thought...

**Comment by kmjonsson** [comment]
This is fixed with: https://github.com/sgas/bart/commit/3cc65f79ffa26564785dc3eedfa1941cf48f7f8f

**Comment by bhmevik** [comment]
Good! Then I'll close this issue.
