### ISSUE TITLE
Problems with stderr_level

### ISSUE THREAD

**Issue by bhmevik** [sgas/bart#31]
There are three problems with the `stderr_level` feature, in decreasing order of importance:

1) It seems only to have been implemented for `bart-logger`, not for `bart-registrant`.
2) It is not documented, except as a line in `documents/etc/bart.conf`
3) That line says `#stderr_level=ERROR  # Uncomment to have Errors written to stderr`, but doing that produces the following error from `bart-logger`:
```
Traceback (most recent call last):
  File "/bin/bart-logger", line 130, in <module>
    main()
  File "/bin/bart-logger", line 57, in main
    stderr_handler.setLevel(stderr_level)
  File "/usr/lib64/python2.7/logging/__init__.py", line 711, in setLevel
    self.level = _checkLevel(level)
  File "/usr/lib64/python2.7/logging/__init__.py", line 187, in _checkLevel
    raise ValueError("Unknown level: %r" % level)
ValueError: Unknown level: 'ERROR  # Uncomment to have Errors written to stderr'
```
So one has to remove also the comment at the end of the line.  Perhaps move the comment to the line before in the example conf file?

**Comment by edelmann** [comment]
You are right on all three points - thanks for the report.
I'll try to do something during the nest few days.

**Comment by edelmann** [comment]
1 & 3 are now fixed.

A note on point 1: Since bart-registrant uses 'twisted.python.log' to handle logs, while bart-logger uses 'logging', their behaviours are still not identical, but at least somewhere in the same direction.
