### ISSUE TITLE
Missing state in slurm.py for slurm versions older than 17.11.0

### ISSUE THREAD

**Issue by magnusu2** [sgas/bart#37]
Timeout, to, is missing from the list of states on line 102 in slurm.py, which assigns command (sacct) for versions of slurm older than 17.11.0

101        if versioncmp(sacct_version, "17.11.0") < 0:
102           command = COMMAND % ('ca,cd,f,nf,pr,rq', state_starttime, self.end_str)
103       else:
104            command = COMMAND % ('ca,cd,f,nf,pr,rq,to,oom', state_starttime, sel

**Comment by edelmann** [comment]
Yes, that's deliberate - it was very specifically to exclude 'to' from the statelist for older sacct versions that the version check was implemented. (The commit is here https://github.com/sgas/bart/commit/ce46332dc68ccd5ff227b3bd7777d7fc7267fc88)

I don't remember much of the case anymore, but I have a vague recollection of older sacct versions complaining about this unrecognized 'to'-state.  Is that wrong?  Do old sacct versions actually recognize 'to'?

**Comment by magnusu2** [comment]
We have used slurm.py with the 'to'-state (timeout) on different 
machines for more than five years without any problem. I have reasons to 
believe that it was OK at least as far back as slurm 2.6.5, because I 
have found a tarball from that time with that version number. Logic also 
dictates that the state would never have been part of the list, if it 
didn't work at the time of writing. We are currently running slurm 
17.02.6, which is the latest version available through yum. Thus, it 
would seem like something happened temporarily between this version and 
17.11.0, which is the version checked for as the oldest possible for 
'to' after the commit.

As far as accounting goes, timeout is a very important state. Without 
it, jobs that hit the walltime limit would disappear without a trace. I 
have checked that none of the other state flags is to able pick up such 
jobs. Thus, in my opinion, the omission of 'to' from the statelist is a 
serious bug, even if it was deliberate.

Best regards,
Magnus

**Comment by edelmann** [comment]
OK; I put 'to' back in the list of states, also for older slurm versions.

I just wonder from where I got the idea that 'to' wouldn't be supported by old slurm versions ...
