### ISSUE TITLE
No logging output on python 2.6

### ISSUE THREAD

**Issue by Micket** [sgas/bart#38]
Being stuck with an old CentOS 6 system, I encountered a problem with logging.
It should use integral values defined by the library: e.g. `logging.DEBUG` instead of using strings `"DEBUG"`.
https://github.com/sgas/bart/blob/master/bart-logger#L39
Seems like it just happens to work anyway on newer versions of python, but the correct value should be an int even in python3.

**Comment by edelmann** [comment]
Hi,
Just committed a fix for this (see https://github.com/sgas/bart/commit/5efe54e2d363cb5b66c72bfcc186ebe739650fdd).

Unfortunately I don't have CentOS 6 anywhere near / too lazy to set up such a machine, but at least it works on CentOS7 with python 2.7 and 3.6
